PREFERRED_URL_SCHEME = 'https' 

# Application defined config variables
GEOSERVER_ENDPOINT = ''
SLD_ENDPOINT = ''
CODES_ENDPOINT = ''
RESULT_ENDPOINT = ''
STATION_ENDPOINT = ''
BIOLOGICAL_RESULT_ENDPOINT = ''

GA_TRACKING_CODE = ''